// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5LNrl7YyK1PJcD5Zz2eJuJKQvixsuFGg',
    appId: '1:920071020883:web:5e9de8691a518325e081a6',
    messagingSenderId: '920071020883',
    projectId: 'fitness-app-project-1c5e3',
    authDomain: 'fitness-app-project-1c5e3.firebaseapp.com',
    storageBucket: 'fitness-app-project-1c5e3.appspot.com',
    measurementId: 'G-39JS2M52YE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJw_gV6uAWtMJIU_AKO23rCQnWtdUlAQ0',
    appId: '1:920071020883:android:1016dbaadc6fef63e081a6',
    messagingSenderId: '920071020883',
    projectId: 'fitness-app-project-1c5e3',
    storageBucket: 'fitness-app-project-1c5e3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARJ31sxKK7nqJwPlEdNUJQawg0h9IVSiE',
    appId: '1:920071020883:ios:06bb0cec5fa896d0e081a6',
    messagingSenderId: '920071020883',
    projectId: 'fitness-app-project-1c5e3',
    storageBucket: 'fitness-app-project-1c5e3.appspot.com',
    iosBundleId: 'com.example.fitnessAppProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARJ31sxKK7nqJwPlEdNUJQawg0h9IVSiE',
    appId: '1:920071020883:ios:06bb0cec5fa896d0e081a6',
    messagingSenderId: '920071020883',
    projectId: 'fitness-app-project-1c5e3',
    storageBucket: 'fitness-app-project-1c5e3.appspot.com',
    iosBundleId: 'com.example.fitnessAppProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5LNrl7YyK1PJcD5Zz2eJuJKQvixsuFGg',
    appId: '1:920071020883:web:7db5c9b1db239464e081a6',
    messagingSenderId: '920071020883',
    projectId: 'fitness-app-project-1c5e3',
    authDomain: 'fitness-app-project-1c5e3.firebaseapp.com',
    storageBucket: 'fitness-app-project-1c5e3.appspot.com',
    measurementId: 'G-JTYPGWNW6W',
  );
}
